export const FETCH_CONTINENTS_DATA = 'FETCH_CONTINENTS_DATA';
export const FETCH_COUNTRIES_DATA = 'FETCH_COUNTRIES_DATA';
export const UPDATE_CONTINENT_SELECTED = 'UPDATE_CONTINENT_SELECTED'; 
export const UPDATE_CONTINENT_UNSELECTED = 'UPDATE_CONTINENT_UNSELECTED';
export const UPDATE_COUNTRIES_TO_DISPLAY_FLAGS = 'UPDATE_COUNTRIES_TO_DISPLAY_FLAGS';